(function(){
"use strict";
const cfg=window.KIP_CONFIG||window.KIP_SUPABASE||{};
const SUPABASE_URL=cfg.SUPABASE_URL||cfg.url||"";
const SUPABASE_ANON_KEY=cfg.SUPABASE_ANON_KEY||cfg.anonKey||"";
let sb=null,allRows=[],filtered=[];
const $=id=>document.getElementById(id);
const loginSection=$('loginSection'),dashboardSection=$('dashboardSection'),signOutBtn=$('signOutBtn'),loginBtn=$('loginBtn'),loginMessage=$('loginMessage'),resultsBody=$('resultsBody'),searchInput=$('searchInput'),versionFilter=$('versionFilter'),statusFilter=$('statusFilter'),detailModal=$('detailModal'),detailTitle=$('detailTitle'),detailSubtitle=$('detailSubtitle'),detailBody=$('detailBody');
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;")}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function fmtTime(s){s=Math.max(0,Math.round(n(s)));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function fmtDate(v){if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?'-':d.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function parseArray(v){if(Array.isArray(v))return v;if(typeof v==='string'){try{const p=JSON.parse(v);return Array.isArray(p)?p:[]}catch(_e){return[]}}return[]}
function showMessage(type,text){loginMessage.className='message show '+type;loginMessage.textContent=text}
function normalize(r){return{id:r.id,date:r.submitted_at||r.created_at,participant:r.participant_name||'-',whatsapp:r.whatsapp||'-',institution:r.institution||'-',version:r.version||'-',raw:n(r.raw_score),accuracy:n(r.accuracy),time:n(r.elapsed_seconds),unanswered:n(r.unanswered),auto:!!r.auto_submitted,p1:n(r.part1_score),p2:n(r.part2_score),p3:n(r.part3_score),p4:n(r.part4_score),p5:n(r.part5_score),types:parseArray(r.type_stats),items:parseArray(r.item_results),source:r}}
function renderStats(rows){$('statTotal').textContent=rows.length;$('statRaw').textContent=`${avg(rows.map(x=>x.raw)).toFixed(1)}/50`;$('statAccuracy').textContent=`${avg(rows.map(x=>x.accuracy)).toFixed(0)}%`;$('statTime').textContent=fmtTime(avg(rows.map(x=>x.time)));$('statAuto').textContent=rows.filter(x=>x.auto).length}
function fillVersions(){const vals=[...new Set(allRows.map(x=>x.version).filter(Boolean))].sort(),cur=versionFilter.value;versionFilter.innerHTML='<option value="">All versions</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vals.includes(cur))versionFilter.value=cur}
function renderTable(rows){if(!rows.length){resultsBody.innerHTML='<tr><td colspan="16">No Reading attempts found.</td></tr>';$('footerNote').textContent='0 records.';return}resultsBody.innerHTML=rows.map(r=>`<tr><td>${esc(fmtDate(r.date))}</td><td><strong>${esc(r.participant)}</strong></td><td>${esc(r.whatsapp)}</td><td>${esc(r.institution)}</td><td><span class="badge blue">${esc(r.version)}</span></td><td><strong>${r.raw}/50</strong></td><td>${r.p1}/10</td><td>${r.p2}/10</td><td>${r.p3}/11</td><td>${r.p4}/10</td><td>${r.p5}/9</td><td>${r.accuracy}%</td><td>${fmtTime(r.time)}</td><td>${r.unanswered}</td><td>${r.auto?'<span class="badge red">Auto-submitted</span>':'<span class="badge green">Completed</span>'}</td><td><button class="view" data-id="${esc(r.id)}">View</button></td></tr>`).join('');$('footerNote').textContent=`${rows.length} Reading attempt(s) shown.`}
function applyFilter(){const q=searchInput.value.trim().toLowerCase(),ver=versionFilter.value,st=statusFilter.value;filtered=allRows.filter(r=>{if(q&&![r.participant,r.whatsapp,r.institution,r.version].join(' ').toLowerCase().includes(q))return false;if(ver&&r.version!==ver)return false;if(st==='completed'&&r.auto)return false;if(st==='auto'&&!r.auto)return false;return true});renderStats(filtered);renderTable(filtered)}
async function loadResults(){resultsBody.innerHTML='<tr><td colspan="16">Loading...</td></tr>';try{let {data,error}=await sb.from('reading_attempts').select('*').order('submitted_at',{ascending:false});if(error){({data,error}=await sb.from('reading_attempts').select('*'))}if(error)throw error;allRows=(data||[]).map(normalize).sort((a,b)=>new Date(b.date)-new Date(a.date));fillVersions();applyFilter()}catch(err){console.error(err);resultsBody.innerHTML=`<tr><td colspan="16">Failed to load Reading data: ${esc(err.message||'Unknown error')}</td></tr>`}}
function openDetail(r){detailTitle.textContent=r.participant;detailSubtitle.textContent=`${fmtDate(r.date)} · ${r.whatsapp} · Version ${r.version}`;const typeHtml=r.types.length?'<div class="type-chips">'+r.types.map(x=>`<span class="chip">${esc(x.type)}: ${n(x.correct)}/${n(x.total)} (${n(x.pct)}%)</span>`).join('')+'</div>':'';const itemHtml=r.items.length?`<div class="table-wrap"><table style="min-width:900px"><thead><tr><th>Q</th><th>Part</th><th>Type</th><th>Selected</th><th>Correct</th><th>Result</th><th>Flag</th></tr></thead><tbody>${r.items.map(x=>`<tr><td><strong>${esc(x.item_no)}</strong></td><td>${esc(x.part)}</td><td>${esc(x.type)}</td><td>${esc(x.selected??'—')}</td><td>${esc(x.correct??'—')}</td><td class="${x.unanswered?'unanswered':x.is_correct?'correct':'wrong'}">${x.unanswered?'Unanswered':x.is_correct?'Correct':'Incorrect'}</td><td>${x.flagged?'★':'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p>No item-level data available.</p>';detailBody.innerHTML=`<div class="detail-stats"><div class="mini"><span>Raw</span><strong>${r.raw}/50</strong></div><div class="mini"><span>Accuracy</span><strong>${r.accuracy}%</strong></div><div class="mini"><span>Time</span><strong>${fmtTime(r.time)}</strong></div><div class="mini"><span>Unanswered</span><strong>${r.unanswered}</strong></div><div class="mini"><span>Status</span><strong style="font-size:13px">${r.auto?'Auto-submitted':'Completed'}</strong></div></div>${typeHtml}${itemHtml}`;detailModal.classList.remove('hidden');document.body.style.overflow='hidden'}
function closeDetail(){detailModal.classList.add('hidden');document.body.style.overflow=''}
function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}
function exportCsv(){if(!filtered.length){alert('No records to export.');return}const heads=['Date','Participant','WhatsApp','Institution','Version','Raw','P1','P2','P3','P4','P5','Accuracy','Elapsed Seconds','Unanswered','Status'],lines=[heads.map(csvEscape).join(',')];filtered.forEach(r=>lines.push([fmtDate(r.date),r.participant,r.whatsapp,r.institution,r.version,r.raw,r.p1,r.p2,r.p3,r.p4,r.p5,r.accuracy,r.time,r.unanswered,r.auto?'Auto-submitted':'Completed'].map(csvEscape).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`KIP-Reading-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function showLogin(){loginSection.classList.remove('hidden');dashboardSection.classList.add('hidden');signOutBtn.classList.add('hidden')}
async function showDashboard(){loginSection.classList.add('hidden');dashboardSection.classList.remove('hidden');signOutBtn.classList.remove('hidden');await loadResults()}
async function signIn(){loginMessage.className='message';const email=$('email').value.trim(),password=$('password').value;if(!email||!password){showMessage('error','Isi email dan password.');return}loginBtn.disabled=true;loginBtn.textContent='Signing in...';try{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;if(!data?.session)throw new Error('Session tidak terbentuk.');await showDashboard()}catch(err){showMessage('error',err.message||'Login gagal.')}finally{loginBtn.disabled=false;loginBtn.textContent='Sign In'}}
async function init(){if(!SUPABASE_URL||!SUPABASE_ANON_KEY){showLogin();showMessage('error','config.js belum terbaca.');return}if(!window.supabase||typeof window.supabase.createClient!=='function'){showLogin();showMessage('error','Supabase SDK gagal dimuat.');return}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data}=await sb.auth.getSession();if(data?.session)await showDashboard();else showLogin()}
loginBtn.addEventListener('click',signIn);$('password').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});signOutBtn.addEventListener('click',async()=>{await sb.auth.signOut();showLogin()});$('refreshBtn').addEventListener('click',loadResults);$('exportBtn').addEventListener('click',exportCsv);searchInput.addEventListener('input',applyFilter);versionFilter.addEventListener('change',applyFilter);statusFilter.addEventListener('change',applyFilter);resultsBody.addEventListener('click',e=>{const b=e.target.closest('.view');if(!b)return;const r=allRows.find(x=>String(x.id)===String(b.dataset.id));if(r)openDetail(r)});$('detailCloseBtn').addEventListener('click',closeDetail);detailModal.addEventListener('click',e=>{if(e.target===detailModal)closeDetail()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!detailModal.classList.contains('hidden'))closeDetail()});init();
})();